### ISSUE TITLE
Error submitting a new post

### ISSUE THREAD

**Issue by joelzehring** [phil4lif/Michelangelo#45]
Error message: "Unhandled rejection SequelizeDatabaseError: Unknown column 'UserId' in 'field list'"

**Comment by phil4lif** [comment]
is this error happening on the heroku deployment or on your local machine or both?

**Comment by phil4lif** [comment]
try going into your mysql workbench and refresh your database and right click on each of your tables in the michelangelo_db and click drop table
then try to run it again... I have a feeling it is trying to add to your tables that don't have the new column for the signed in user, everyone will probably have to do this to get it working locally

**Comment by joelzehring** [comment]
This seems to be resolved. Closing this issue.
