### ISSUE TITLE
Hardcode post categories to get those routes and views working

### ISSUE THREAD

**Issue by joelzehring** [phil4lif/Michelangelo#8]
Add in categories for MVP.

cooking
diy
travel
soccer
inspirational quotes
music

20200321 Categories can be added to posts but still need to develop UI and routes to show posts in a specific category.

**Comment by phil4lif** [comment]
I think I've completed this, the boz and marcia can style this table now.  Maybe we should do the thing with the body like we did on let's get paid and have a see more button that opens a modal with the full body of the posts in it?
